---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent
  namespace: jetstack-secure
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: agent
    spec:
      serviceAccountName: agent
      volumes:
        - name: config
          configMap:
            name: agent-config
        - name: credentials
          secret:
            secretName: agent-credentials
      containers:
        - name: agent
          image: quay.io/jetstack/preflight:v0.1.35

          args:
            - "agent"
            - "-c"
            - "/etc/jetstack-secure/agent/config/config.yaml"

            - "-k"
            - "/etc/jetstack-secure/agent/credentials/credentials.json"

            - "-p"
            - "0h1m0s"
          volumeMounts:
            - name: config
              mountPath: "/etc/jetstack-secure/agent/config"
              readOnly: true

            - name: credentials
              mountPath: /etc/jetstack-secure/agent/credentials
              readOnly: true

          resources:
            requests:
              memory: {{ .Values.agent.resources.requests.memory }}
              cpu: {{ .Values.agent.resources.requests.cpu }}
            limits:
              memory: {{ .Values.agent.resources.limits.memory }}
              cpu: {{ .Values.agent.resources.limits.cpu }}
