---
apiVersion: keymaker.equinixmetal.com/v1
kind: ExternalSecretPull
metadata:
  name: agent-credentials
spec:
  backend: ssm
  mappings:
    - key: /prod/jetstack-secure/jetstack-secure/v1
      name: credentials.json
